#include "functions\applyConfig.au3"
#include "functions\readConfig.au3"
#include "functions\saveConfig.au3"
#include "functions\Config_Heros\applyConfig.au3"
#include "functions\Config_Heros\readConfig.au3"
#include "functions\Config_Heros\saveConfig.au3"